apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: 1
  template: 
    metadata:
      labels:
         app: {{ .Release.Name }}-backend
      annotations:
        pod.beta.kubernetes.io/init-containers: |-
          [
            {
              "name": "mysql-listener",
              "image": "alpine",
              "imagePullPolicy": "IfNotPresent",
              "command": [
                "sh", "-c",
                "for i in $(seq 1 200); do nc -z -w3 {{ .Release.Name }}-mysql 3306 && exit 0 || sleep 3; done; exit 1"
              ]
            }
          ]
    spec:
      containers:
      - name: backend
        image: '{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}'
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: ["entrypoint.sh", "{{ .Values.backend.port }}"]
        env:
            - name: "MYSQL_DATABASE"
              value: {{ .Values.mysql.mysqlDatabase }}
            - name: "MYSQL_USER"
              value: {{ .Values.mysql.mysqlUser }}
            - name: "MYSQL_PASSWORD"
              value: {{ .Values.mysql.mysqlPassword }}
            - name: "MYSQL_HOST"
              value: "{{ .Release.Name }}-mysql"
            - name: "GALAXY_URL"
              value: {{ .Values.galaxy_url }}
            - name: "GALAXY_API_KEY"
              value: {{ .Values.galaxy_api_key }}
        ports:
        - containerPort: {{ .Values.backend.port }}
