apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-metadata
spec:
  type: 
  ports:
  - name: tcp
    port: {{ .Values.metadata.port }}
    targetPort: {{ .Values.metadata.port }}
  selector:
    app: {{ .Release.Name }}-metadata
